"use client";

import React, { useState } from 'react';
import { Card } from '../ui/Card';
import styles from './ArtifactViewer.module.css';

export const ArtifactViewer: React.FC = () => {
  const [selectedFile, setSelectedFile] = useState('src/app/page.tsx');

  const files = [
    { name: 'src/app/page.tsx', type: 'typescript' },
    { name: 'src/components/Button.tsx', type: 'typescript' },
    { name: 'package.json', type: 'json' },
    { name: 'schema.prisma', type: 'prisma' },
  ];

  const mockCode = `import React from 'react';

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl">
          Generated by OpenClaw Frontend Agent
        </p>
      </div>
    </main>
  );
}`;

  return (
    <div className={styles.container}>
      <Card className={styles.sidebar}>
        <h3 className="font-semibold mb-4 text-sm text-secondary uppercase tracking-wider">File Explorer</h3>
        <div className="flex-col gap-1">
          {files.map(file => (
            <button
              key={file.name}
              className={`${styles.fileBtn} ${selectedFile === file.name ? styles.activeFile : ''}`}
              onClick={() => setSelectedFile(file.name)}
            >
              📄 {file.name}
            </button>
          ))}
        </div>
      </Card>
      
      <Card className={styles.editor}>
        <div className={styles.editorHeader}>
          <span>{selectedFile}</span>
          <button className={styles.copyBtn}>Copy</button>
        </div>
        <pre className={styles.codeArea}>
          <code>{mockCode}</code>
        </pre>
      </Card>
    </div>
  );
};
